spring:
  application:
    name: bookstore

  datasource:
    url: jdbc:sqlite:sqlite_db/bookstore
    driver-class-name: org.sqlite.JDBC

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
